name: Create Pre-Production Branch with Develop Changes

on:
  workflow_dispatch: # 手動実行用

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ブランチ作成に必要

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main # mainブランチをチェックアウト

      - name: Create pre-production branch
        run: |
          git checkout -b pre-production
          git push origin pre-production

      - name: Fetch develop branch
        run: |
          git fetch origin develop:develop

      - name: Rebase develop onto pre-production
        run: |
          git checkout pre-production
          git rebase develop
          git push --force origin pre-production

      - name: Confirm rebase
        run: |
          echo "Branch pre-production rebased with develop."