name: Create Pre-Production Branch and Pull Request

on:
  workflow_dispatch: # 手動実行用

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ブランチ作成・Pushに必要
      pull-requests: write # Pull Request作成に必要

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create pre-production branch
        run: |
          git checkout -b pre-production
          git push origin pre-production

      - name: Fetch develop branch
        run: |
          git fetch origin develop:develop

      - name: Rebase develop onto pre-production
        run: |
          git checkout pre-production
          git rebase develop
          git push --force origin pre-production

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh pr create \
            --base main \
            --head pre-production \
            --title "Rebase develop into pre-production" \
            --body "This PR rebases the develop branch into pre-production. Review and merge when ready."